package role_permission

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"identity/actions"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (RolePermission)
// DB Table: Plural (role_permissions)
// Resource: Plural (RolePermissions)
// Path: Plural (/role_permissions)
// View Template Folder: Plural (/templates/role_permissions/)

// RolePermissionsResource is the resource for the RolePermission model
type RolePermissionsResource struct {
	buffalo.Resource
}

// List gets all RolePermissions. This function is mapped to the path
// GET /role_permissions
func (v RolePermissionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	role_permissions := &RolePermissions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all RolePermissions from the DB
	if err := q.All(role_permissions); err != nil {
		return err
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(200, actions.R.JSON(role_permissions))
	}).Respond(c)
}

// Show gets the data for one RolePermission. This function is mapped to
// the path GET /role_permissions/{role_permission_id}
func (v RolePermissionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty RolePermission
	role_permission := &RolePermission{}

	// To find the RolePermission the parameter role_permission_id is used.
	if err := tx.Find(role_permission, c.Param("role_permission_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(200, actions.R.JSON(role_permission))
	}).Respond(c)
}

// Create adds a RolePermission to the DB. This function is mapped to the
// path POST /role_permissions
func (v RolePermissionsResource) Create(c buffalo.Context) error {
	// Allocate an empty RolePermission
	role_permission := &RolePermission{}

	// Bind role_permission to the html form elements
	if err := c.Bind(role_permission); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(role_permission)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, actions.R.JSON(verrs))
		}).Respond(c)
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, actions.R.JSON(role_permission))
	}).Respond(c)
}

// Update changes a RolePermission in the DB. This function is mapped to
// the path PUT /role_permissions/{role_permission_id}
func (v RolePermissionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty RolePermission
	role_permission := &RolePermission{}

	if err := tx.Find(role_permission, c.Param("role_permission_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind RolePermission to the html form elements
	if err := c.Bind(role_permission); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(role_permission)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, actions.R.JSON(verrs))
		}).Respond(c)
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, actions.R.JSON(role_permission))
	}).Respond(c)
}

// Destroy deletes a RolePermission from the DB. This function is mapped
// to the path DELETE /role_permissions/{role_permission_id}
func (v RolePermissionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty RolePermission
	role_permission := &RolePermission{}

	// To find the RolePermission the parameter role_permission_id is used.
	if err := tx.Find(role_permission, c.Param("role_permission_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(role_permission); err != nil {
		return err
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, actions.R.JSON(role_permission))
	}).Respond(c)
}
