package user_role

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"identity/actions"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (UserRole)
// DB Table: Plural (user_roles)
// Resource: Plural (UserRoles)
// Path: Plural (/user_roles)
// View Template Folder: Plural (/templates/user_roles/)

// UserRolesResource is the resource for the UserRole model
type UserRolesResource struct {
	buffalo.Resource
}

// List gets all UserRoles. This function is mapped to the path
// GET /user_roles
func (v UserRolesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	user_roles := &UserRoles{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all UserRoles from the DB
	if err := q.All(user_roles); err != nil {
		return err
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(200, actions.R.JSON(user_roles))
	}).Respond(c)
}

// Show gets the data for one UserRole. This function is mapped to
// the path GET /user_roles/{user_role_id}
func (v UserRolesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty UserRole
	user_role := &UserRole{}

	// To find the UserRole the parameter user_role_id is used.
	if err := tx.Find(user_role, c.Param("user_role_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(200, actions.R.JSON(user_role))
	}).Respond(c)
}

// Create adds a UserRole to the DB. This function is mapped to the
// path POST /user_roles
func (v UserRolesResource) Create(c buffalo.Context) error {
	// Allocate an empty UserRole
	user_role := &UserRole{}

	// Bind user_role to the html form elements
	if err := c.Bind(user_role); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(user_role)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, actions.R.JSON(verrs))
		}).Respond(c)
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, actions.R.JSON(user_role))
	}).Respond(c)
}

// Update changes a UserRole in the DB. This function is mapped to
// the path PUT /user_roles/{user_role_id}
func (v UserRolesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty UserRole
	user_role := &UserRole{}

	if err := tx.Find(user_role, c.Param("user_role_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind UserRole to the html form elements
	if err := c.Bind(user_role); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(user_role)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, actions.R.JSON(verrs))
		}).Respond(c)
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, actions.R.JSON(user_role))
	}).Respond(c)
}

// Destroy deletes a UserRole from the DB. This function is mapped
// to the path DELETE /user_roles/{user_role_id}
func (v UserRolesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty UserRole
	user_role := &UserRole{}

	// To find the UserRole the parameter user_role_id is used.
	if err := tx.Find(user_role, c.Param("user_role_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(user_role); err != nil {
		return err
	}

	return responder.Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, actions.R.JSON(user_role))
	}).Respond(c)
}
